import type { ActivityItem, ActivityType, UploadStage } from "./types";
import type { RequestListBadge } from "./requests/types";

export const statusLabels: Record<RequestListBadge, string> = {
  unopened: "טרם נפתחה",
  active: "פעילה",
  closed: "סגורה",
  expired: "פגה",
  revoked: "בוטלה",
};

export const statusBadgeLabels: Record<RequestListBadge, string> = {
  unopened: "לא נפתחה",
  active: "פעילה",
  closed: "סגורה",
  expired: "פגה",
  revoked: "בוטלה",
};

export const uploadStageLabels: Record<UploadStage, string> = {
  reading: "קוראים את המסמך",
  identifying: "מזהים את סוג המסמך",
  extracting: "מחלצים פרטים",
  matching: "בודקים התאמה לסלוט",
  action_required: "ממתין להחלטה שלך",
  completed: "הושלם",
  failed: "לא הצליח",
};

export const activityTypeLabels: Record<ActivityType, string> = {
  action: "נדרשת פעולה",
  alert: "התראה",
  update: "עדכון",
  processing: "סייקל פעיל",
};

export const extractedFieldLabels: Record<string, string> = {
  fullName: "שם העובד",
  identityNumber: "מספר מזהה",
  title: "כותרת המסמך המקורית",
  credentialNumber: "מספר תעודה",
  issuer: "גוף מנפיק",
  issuedOn: "תאריך הנפקה",
  validFrom: "בתוקף מ־",
  expiresOn: "בתוקף עד",
  permissionsHe: "היקפים והרשאות",
  restrictionsHe: "הגבלות",
};

export const copy = {
  appTitle: "פעילות",
  appName: "סרטיפי",
  settingsTitle: "הגדרות",
  requestsTitle: "בקשות",
  navFeed: "פיד",
  navCreate: "בקשה חדשה",
  navUsers: "בקשות",
  upload: "העלאה",
  uploadDocument: "העלאה",
  processingOne: "מעבדים מסמך…",
  processingMany: (n: number) => `מעבדים ${n} מסמכים…`,
  jobsTitle: "עיבוד מסמכים",
  jobsEmpty: "אין מסמכים בעיבוד",
  captured: "המסמך נקלט",
  gallery: "גלריה",
  camera: "צילום",
  pdf: "קובץ PDF",
  dropHint: "גררו קובץ לכאן או בחרו מהמחשב",
  pickFile: "בחירת קובץ",
  invalidFile: "אפשר להעלות תמונה או PDF בלבד",
  composerTitle: "העלאת קובץ",
  allClearTitle: "אין הגשות שדורשות טיפול",
  allClearBody: "אין הגשות ממתינות או שדורשות בדיקה כרגע.",
  feedTitle: "פעילות אחרונה",
  identityNumberLabel: "מספר מזהה",
  postActionsTitle: "פעולות",
  uploadNew: "העלה קובץ",
  openProcessing: "פתח עיבוד",
  processingSupport: "קוראים ומחלצים את פרטי המסמכים",
  resultListTitle: "תוצאות",
  resultListEmpty: "אין פריטים להצגה",
  confirmExpiryTitle: "אישור תאריך תוקף",
  evidenceCropLabel: "קטע מהמסמך",

  requestsSearchPlaceholder: "חיפוש לפי שם בקשה או מקבל",
  requestsEmptyTitle: "עדיין אין בקשות",
  requestsEmptyBody: "צרו בקשת מסמכים ראשונה ושלחו קישור למקבל.",
  requestsNoResultsTitle: "לא נמצאו תוצאות",
  requestsNoResultsBody: (query: string) => `לא נמצאה בקשה שמתאימה ל־”${query}”`,
  newRequest: "בקשה חדשה",
  pickRequestForDetails: "בחרו בקשה מהרשימה כדי לראות את הפרטים",
  requestNotFound: "הבקשה לא נמצאה",

  createRequestTitle: "יצירת אירוע חדש",
  createRequestName: "שם האירוע",
  createRecipientName: "שם איש הקשר",
  createPhone: "טלפון",
  createEmail: "אימייל",
  createDocuments: "מסמכים לכל עובד",
  createDocumentLabel: "שם המסמך",
  createDocumentHint: "למשל אישור עבודה בגובה",
  createAddDocument: "הוספת מסמך",
  createExpiry: "תפוגת הקישור",
  createSubmit: "צור בקשה",
  createNeedContact: "נדרש טלפון או אימייל",
  createNeedSlot: "נדרש מסמך אחד לפחות",
  createNeedDetails: "נדרשים שם אירוע, איש קשר וטלפון או אימייל",
  createNeedValidContact: "נדרש טלפון בן 10 ספרות או אימייל תקין",
  createStepDetails: "פרטים",
  createStepDocuments: "מסמכים דרושים",
  createStepSchedule: "תזמון האירוע",
  createStepSummary: "סיכום",
  createNext: "הבא",
  createBack: "חזור",
  createFinish: "סיום",

  sectionSlots: "מסמכים מבוקשים",
  sectionWorkers: "הגשות עובדים",
  noWorkersYet: "עדיין לא הוגשו עובדים",
  workersSubmitted: (n: number) => (n === 1 ? "עובד אחד הוגש" : `${n} עובדים הוגשו`),
  workersComplete: (n: number) => `${n} שלמים`,
  workersNeedsReview: (n: number) => `${n} דורשים טיפול`,
  linkStatus: "סטטוס הקישור",
  expiresAtLabel: "תפוגה",
  recipientLabel: "מקבל",

  formSave: "שמירה",
  formSaving: "שומרים…",
  formCancel: "ביטול",
  formFullName: "שם מלא",
  formIdentity: "מספר מזהה",

  viewerOriginalSection: "המסמך המקורי",
  viewerExtractedSection: "פרטים שחולצו",
  viewerFileName: "שם הקובץ",
  viewerFileType: "סוג קובץ",
  viewerFileSize: "גודל",
  viewerPages: "עמודים",
  viewerUploadedOn: "הועלה בתאריך",
  viewerClose: "סגור",
  viewerStatusLabel: "סטטוס",

  sheetRelatedRequest: "בקשה מקושרת",
  sheetRelatedWorker: "עובד מקומי",
  sheetDocumentSection: "מסמך",
  sheetInsightsSection: "תובנות",
  sheetEvidence: "מה זיהינו במסמך",
  sheetResolvedToast: "הטיפול הושלם",
  confirmFieldTitle: "אישור פרט שחולץ",
  confirmFieldExtracted: "הערך שזיהינו",
  confirmFieldConfirm: "אישור הערך",
  confirmFieldFix: "שמירת תיקון",
  replaceFileAction: "העלאת קובץ חדש",
  remindLaterAction: "הזכר לי מאוחר יותר",
  remindLaterToast: "נזכיר שוב מאוחר יותר",
  copiedToast: "ההודעה הועתקה",
  linkCopiedToast: "הקישור הועתק",
  nativeShareAction: "שיתוף",
  uploadMyselfAction: "העלה מסמך בעצמי",
  renewMessageLabel: "הודעה מוכנה לשליחה",
  renewLinkLabel: "קישור העלאה",
  requestCreatedToast: "הבקשה מוכנה לשליחה",
  requestClosedToast: "הבקשה נסגרה",
  requestReopenedToast: "הבקשה נפתחה מחדש",
  requestRevokedToast: "הבקשה בוטלה",
  requestExtendedToast: "תוקף הקישור הוארך",
  requestReopenBlocked: "אי אפשר לפתוח מחדש לפני הארכת התוקף",
  requestExtendBlocked: "אי אפשר להאריך את הבקשה הזו",
  workerSubmittedToast: "ההגשה התקבלה",
  workerApprovedToast: "העובד אושר בבקשה",
  reuploadReadyToast: "קישור העלאה חוזרת מוכן",
  answerError: "לא הצלחנו להשלים את הפעולה",
  documentDetails: "פרטי המסמך",
  confirmAndContinue: "אישור והמשך",
  waitingForUpdatedDocument: "ממתינים למסמך מעודכן",
  processingDocument: "מעבדים את המסמך…",
  noExpiryLabel: "ללא תפוגה",
  extractedFromDocument: "חולץ מהמסמך",
  remindLater: "הזכר לי מאוחר יותר",

  shareCopyLink: "העתקת קישור",
  shareWhatsapp: "שתף בוואטסאפ",
  shareEmail: "שלח במייל",

  requestPageTitle: "העלאת מסמכים",
  requestExplanation: (title: string) =>
    `התבקשת להגיש מסמכים עבור: ${title}. אפשר להוסיף כמה עובדים תחת אותו קישור.`,
  requestPrivacyNote: "הקבצים ישמשו רק לבקשה הזו ולא יוצגו מחוץ לה.",
  requestUploadCta: "צילום או העלאת קובץ",
  requestUploading: "מעלים את הקובץ…",
  requestSuccessTitle: "ההגשה התקבלה, תודה!",
  requestSuccessBody: "אפשר להוסיף עובד נוסף באותו קישור.",
  requestAddAnother: "הוסף עובד נוסף",
  requestAddWorker: "הוסף עובד",
  requestSubmitWorker: "שלח את העובד",
  requestExpiredTitle: "הקישור כבר לא בתוקף",
  requestExpiredBody: "אפשר לבקש קישור חדש ממי ששלח לך את ההודעה.",
  requestInvalidTitle: "הקישור לא נמצא",
  requestCancelledTitle: "הבקשה בוטלה",
  requestCancelledBody: "מי ששלח את הבקשה ביטל אותה.",
  requestClosedTitle: "הבקשה נסגרה",
  requestClosedBody: "לא ניתן להגיש עובדים נוספים.",
  requestFileError: "לא הצלחנו לקלוט את הקובץ. נסו קובץ אחר.",
  requestExpiresOn: (date: string) => `הבקשה בתוקף עד ${date}`,
  requestedDocLabel: "המסמך המבוקש",
  reuploadTitle: "העלאת קובץ לעובד",
  reuploadResolvedTitle: "הקובץ כבר אושר",
  reuploadResolvedBody: "אין צורך להעלות שוב לקישור הזה.",

  demoTitle: "בקרת דמו",
  demoNextOutcome: "תוצאת ההעלאה הבאה",
  demoReset: "איפוס נתוני הדגמה",
  demoResetDone: "הנתונים אופסו",
  demoForceState: "מצב תצוגה כפוי",
  demoPauseJobs: "השהה עיבוד",
  demoResumeJobs: "המשך עיבוד",
  demoCompleteJobs: "השלם את כל העיבודים",
  demoScenarios: "תרחישי העלאה",
  demoQaSection: "מצב בדיקות קצה",
  demoQaLoad: "טען את כל מקרי הקצה",
  demoQaReset: "אפס את מקרי הקצה",
  demoQaRestore: "חזור לנתוני הדמו הרגילים",
  demoQaLoaded: "נטענו כל מקרי הקצה",
  demoQaResetDone: "מקרי הקצה אופסו",
  demoQaRestored: "חזרנו לנתוני הדמו הרגילים",

  viewSource: "צפייה במסמך",
  noExpiryAction: "למסמך אין תאריך תפוגה",
  loadingPersisted: "טוענים את התיק…",
  moreOptions: "אפשרויות נוספות",
  systemContinues: "המערכת תמשיך לאחר האישור",
  continuingTreatment: "ממשיך לטפל במסמך…",
  unknownReviewTitle: "לא הצלחנו להשלים את הטיפול באופן אוטומטי",
  reviewWorkspaceTitle: "בדיקת ההגשה",
  openReview: "בדיקת ההגשה",
  undoAction: "ביטול",
  extractedFacts: "מה שחולץ מהמסמך",
  approveWorker: "אישור העובד",
  uploadForSlot: "העלה קובץ לסלוט",
  requestReupload: "בקש העלאה מחדש",
  extendExpiry: "הארכת תוקף הקישור",
  closeRequest: "סגירת הבקשה",
  reopenRequest: "פתיחה מחדש",
  revokeRequest: "ביטול הבקשה",
  viewRequest: "צפייה בבקשה",
  slotMissing: "חסר",
  slotAccepted: "התקבל",
  slotNeedsReview: "דורש בדיקה",
  slotRejected: "נדחה",
  slotExpired: "פג תוקף",
  slotProcessing: "בעיבוד",
  workerDraft: "טיוטה",
  workerUploading: "מעלה",
  workerProcessing: "בעיבוד",
  workerNeedsReview: "דורש בדיקה",
  workerComplete: "הושלם",
  workerApproved: "אושר בבקשה",
  workerRejected: "נדחה",
};

export function sheetInsightHe(item: ActivityItem): string | undefined {
  return item.metadataHe;
}
